Added work flow

diff --git a/.github/workflows/01-building-block.yml b/.github/workflows/01-building-block.yml
--- a/.github/workflows/01-building-block.yml
+++ b/.github/workflows/01-building-block.yml
@@ -8,3 +8,12 @@ jobs:
         steps:
             - name: Echo Hello World
               run: echo "Hello, World!"
+    echo-goodbye:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Falied Step
+              run: |
+                echo "This step will fail"
+                exit 1
+            - name: Echo Goodbye World
+              run: echo "Goodbye, World!"          
